export const COUNTDOWN_START = 'COUNTDOWN_START';
export const COUNTDOWN_STOP = 'COUNTDOWN_STOP';
export const COUNTDOWN_HISTORY_ADD = 'COUNTDOWN_HISTORY_ADD';
export const COUNTDOWN_HISTORY_REMOVE = 'COUNTDOWN_HISTORY_REMOVE';
